/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        ivy: {
          purple: {
            'extra-light': 'var(--ivy-purple-extra-light)',
            light: 'var(--ivy-purple-light)',
            'kinda-light': 'var(--ivy-purple-kinda-light)',
            DEFAULT: 'var(--ivy-purple)',
            'kinda-dark': 'var(--ivy-purple-kinda-dark)',
            dark: 'var(--ivy-purple-dark)',
            'extra-dark': 'var(--ivy-purple-extra-dark)',
          },
          green: {
            'extra-light': 'var(--ivy-green-extra-light)',
            light: 'var(--ivy-green-light)',
            'kinda-light': 'var(--ivy-green-kinda-light)',
            DEFAULT: 'var(--ivy-green)',
            'kinda-dark': 'var(--ivy-green-kinda-dark)',
            dark: 'var(--ivy-green-dark)',
            'extra-dark': 'var(--ivy-green-extra-dark)',
          },
          red: {
            'extra-light': 'var(--ivy-red-extra-light)',
            light: 'var(--ivy-red-light)',
            'kinda-light': 'var(--ivy-red-kinda-light)',
            DEFAULT: 'var(--ivy-red)',
            'kinda-dark': 'var(--ivy-red-kinda-dark)',
            dark: 'var(--ivy-red-dark)',
            'extra-dark': 'var(--ivy-red-extra-dark)',
          },
          orange: {
            'extra-light': 'var(--ivy-orange-extra-light)',
            light: 'var(--ivy-orange-light)',
            'kinda-light': 'var(--ivy-orange-kinda-light)',
            DEFAULT: 'var(--ivy-orange)',
            'kinda-dark': 'var(--ivy-orange-kinda-dark)',
            dark: 'var(--ivy-orange-dark)',
            'extra-dark': 'var(--ivy-orange-extra-dark)',
          },
          yellow: {
            'extra-light': 'var(--ivy-yellow-extra-light)',
            light: 'var(--ivy-yellow-light)',
            'kinda-light': 'var(--ivy-yellow-kinda-light)',
            DEFAULT: 'var(--ivy-yellow)',
            'kinda-dark': 'var(--ivy-yellow-kinda-dark)',
            dark: 'var(--ivy-yellow-dark)',
            'extra-dark': 'var(--ivy-yellow-extra-dark)',
          },
          blue: {
            'extra-light': 'var(--ivy-blue-extra-light)',
            light: 'var(--ivy-blue-light)',
            'kinda-light': 'var(--ivy-blue-kinda-light)',
            DEFAULT: 'var(--ivy-blue)',
            'kinda-dark': 'var(--ivy-blue-kinda-dark)',
            dark: 'var(--ivy-blue-dark)',
            'extra-dark': 'var(--ivy-blue-extra-dark)',
          },
          pink: {
            'extra-light': 'var(--ivy-pink-extra-light)',
            light: 'var(--ivy-pink-light)',
            'kinda-light': 'var(--ivy-pink-kinda-light)',
            DEFAULT: 'var(--ivy-pink)',
            'kinda-dark': 'var(--ivy-pink-kinda-dark)',
            dark: 'var(--ivy-pink-dark)',
            'extra-dark': 'var(--ivy-pink-extra-dark)',
          },
        },
        primary: 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        secondary: 'var(--secondary)',
        'on-secondary': 'var(--on-secondary)',
        error: 'var(--error)',
        background: 'var(--background)',
        'on-background': 'var(--on-background)',
        surface: 'var(--surface)',
        'on-surface': 'var(--on-surface)',
        'surface-variant': 'var(--surface-variant)',
        outline: 'var(--outline)',
      },
      fontFamily: {
        sans: [
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
};
